basePath: /api/v1
definitions:
  model.Bank:
    properties:
      bankname:
        example: BRI
        type: string
      id:
        example: 1
        type: integer
    type: object
  model.BanksDataResponse:
    properties:
      banks:
        description: List of provinces
        items:
          $ref: '#/definitions/model.Bank'
        type: array
      total_count:
        description: Total number of provinces
        type: integer
    type: object
  model.FailResponse:
    properties:
      msg:
        example: Pesan kesalahan
        type: string
    required:
    - msg
    type: object
host: localhost:8080
info:
  contact:
    email: hegy.febrianto@gmail.com
    name: API Support
    url: http://www.terbitdigitalagency.com
  description: This is a sample API documentation.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API for the get of Data sub district & district in Indonesia
  version: "1.0"
paths:
  /banks:
    get:
      consumes:
      - application/json
      description: banks
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: List of Banks with total count
          schema:
            $ref: '#/definitions/model.BanksDataResponse'
        "206":
          description: Error lain
          schema:
            $ref: '#/definitions/model.FailResponse'
        "207":
          description: Gagal Login
          schema:
            $ref: '#/definitions/model.FailResponse'
        "209":
          description: Invalid JSON input
          schema:
            $ref: '#/definitions/model.FailResponse'
        "210":
          description: Error Middleware Internal
          schema:
            $ref: '#/definitions/model.FailResponse'
        "214":
          description: Data Pengguna Tidak Ditemukan
          schema:
            $ref: '#/definitions/model.FailResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: banks
      tags:
      - banks
      - banks
swagger: "2.0"
tags:
- description: API yang digunakan untuk mendapatkan data banks
  name: banks
